var GAME_LEVELS = [
  ["                                                                                              ",
   "                                                                                              ",
   "                                               b                             o                ",
   "                                 y                                          y                 ",
   "                                 o                     o        y           v                 ",
   "                            y o  o  o y                         v                             ",
   "                                 o               o                                    y       ",
   "            b                    y          y    y     y            y                 v       ",
   "                     o                o                                                      =",
   "                   y   y        a     x                                  y       o            ",
   "                   v            xxxxxxx         o         b              v      xxxxx         ",
   "       y                                       y                                              ",
   "       v                          o                                                           ",
   "             y                 xxxxxxx           o            xxxxxxx                         ",
   "                                      x                                       oo              ",
   "                    x  !x            xx    xxxxxxxxxxxxxxx                 xxxxxxxx           ",
   "    @            xxxx  !xxxxx                                           o                     ",
   "x  xxx   xx      x!!!       x                                         xxxxxxx                 ",
   "          x!!!!!!x!                o                   b                          b           ",
   "          x!!!!!!x!              xxxxx                                                        ",
   "      b   x!!!!!!x!    o   !x        x!!!!x                  y                                ",
   "          xxxxxxxx!  !xx!  !x                                v                                ",
   "                 x!  !!!!  !x                                                                =",
   "                 x!!!    !!!x =              o          o        o          o       o c       ",
   "                 xxxx    xxxx              xxxxxx    xxxxxx     xxxxxx    xxxxxx  xxxxxx      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


   // Level 2
  ["                                  |      |                       ",
   "=                                                                ",
   "           o           o                                        =",
   "           y           y                                         ",
   "     o     v           v      o              o                   ",
   "     y           y            y              y                   ",
   "     v                        v       o      v                   ",
   "                  b                   y                          ",
   "        oo                            v             b            ",
   "        xx                                                       ",
   "                                                                 ",
   "                  ooo                                            ",
   "                xxxxxxx                                          ",
   "                x     x     |                   o        oo      ",
   "              o x     x o                       y     xxxxxxx    ",
   "             xxxx     xxxx                      v           x    ",
   "   @              b             o         o                 x    ",
   "xxxxxxxxx                     xxxxx  |  xxxx                xc   ",
   "        |                                           oo      xx   ",
   "                                                            xv   ",
   "              o        o                b                   x    ",
   "            xxxx     xxxx                                   x    ",
   "                        x                                   x    ",
   " =                o     x      oo               oo         =x    ",
   "     o           xx     x     xxxx             xxxx         x    ",
   "   xxxxx                x=             oo                   x    ",
   "                        x             xxxx             oooo x b  ",
   "                        x                            xxxxxxxx    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


//Level 3
["                                                                       ",
 "                                                                       ",
 "                                                                       ",
 "                                                                       ",
 "   y       y       y       y       y       y       y       y       y   ",
 "   v       v       v       v       v       v       v       v       v   ",
 "                                                                       ",
 "                                                                       ",
 "                                                              b        ",
 "                                                                       ",
 "                                   ooo                                 ",
 "                                  xxxxx           o                    ",
 "                 o   o      o                    xxx                   ",
 "               xxxxxxxxxxo  x                                o         ",
 "=                o  o  oxx  x                               xxx        ",
 "               xxxxxxxx x  ox              o                           ",
 "  @         o  x      x x  xx             xxx                          ",
 "xxxx     oxxxxxx   xxxxoxo  x    b             b b                oo   ",
 "   x   oxxx        x o  xx  x                  b b                xx   ",
 "   x  xxx          x xxxx  ox                           oo             ",
 "   xxxx       xxxxxxox   c xx    b                     xxxx            ",
 "              xo  o  xoxxxxxx                                          ",
 "              x xxxxxx x                 oo                    b       ",
 "              xo   o  ox                xxxx                           ",
 "              xxxxxxxxxx                          o                    ",
 "     a                               o           xxx                   ",
 "    xxx                       xx    xx                                 ",
 "         o    o    o   o    o                                          ",
 "!!!!!!!!xx!!!xx!!!xx!!xxx!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
 "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


//Level 4
["        |         |         |         |                    |   ",
 "                                                               ",
 " c   o      o  o      o  o      o  o      o  o    o            ",
 "xxxxxxx   xxxxxxx   xxxxxxx   xxxxxxx   xxxxxxx   y            ",
 "x   !!!               !!!                 !!!         o        ",
 "x    v                 v                   v          y        ",
 "x                                           o     oo           ",
 "x              b b                          y    xxxx          ",
 "x              b b                     o                       ",
 "x              b b                     y                       ",
 "x                                 o                            ",
 "x                                 y                            ",
 "x                            o              o                  ",
 "x @    oo                    y             xxx     o           ",
 "xxxxx xxxx              o            o     !!!    xxx          ",
 " !!!                    y           xxx     v                  ",
 "= v                 o          o    !!!                  o     ",
 "     o              y         xxx    v                  xx     ",
 "    xxx         o         o   !!!                  o          =",
 "                y        xxx   v                  xxx          ",
 "=        o           o                        o                ",
 "        xxx         xxx                      xxx               ",
 "  o                         a    o o     o                     ",
 " xxx                       xxxx xxxxx xxxxxx                   ",
 "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
 "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


//Win screen
["                                                                     ",
 "                                                                     ",
 "  o                 o  ooooooo  oo     o   oo     o  ooooo  ooooo    ",
 "   o       o       o      o     o o    o   o o    o  o      o    o   ",
 "    o     o o     o       o     o  o   o   o  o   o  oooo   ooooo    ",
 "     o   o   o   o        o     o   o  o   o   o  o  o      o    o   ",
 "      o o     o o         o     o    o o   o    o o  o      o    o   ",
 "       o       o       ooooooo  o     oo   o     oo  ooooo  o    o   ",
 "   @                                                                 ",
 "   y                                                                 ",
 "  xxx                                                                ",
 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
